parameters:
    hgabka_logger.exception_logger.class: 'Hgabka\LoggerBundle\Logger\ExceptionLogger'
    hgabka_logger.exception_notifier.class: 'Hgabka\LoggerBundle\Helper\ExceptionNotifier'

services:
    hgabka_logger.exception_logger:
        class: '%hgabka_logger.exception_logger.class%'
        arguments: ["@logger", '']

    hgabka_logger.exception_notifier:
        class: '%hgabka_logger.exception_notifier.class%'
        arguments: ["@doctrine", "@mailer", "@request_stack", "@hgabka_logger.exception_logger", "%kernel.debug%"]

    hgabka_logger.exception_listener:
        class: Hgabka\LoggerBundle\EventListener\ExceptionListener
        arguments: ["@hgabka_logger.exception_notifier"]
        tags:
            - { name: kernel.event_listener, event: kernel.exception }
